### ISSUE TITLE
Python3中遇到UnicodeEncodeError: 'ascii' codec can't encode characters in ordinal not in range(128)

### ISSUE THREAD

**Issue by Gaoshuang77** [luopeixiang/named_entity_recognition#17]
在运行到crf模型时出现上述错误，查了很久，试了各种方法也没有解决，请问有没有人知道该如何解决呢？
环境：win10 python3.8
编码方式查过了是utf-8没错，但一直出现这个错误。求大神支招！

**Comment by TENGSP** [comment]
同样问题，请问你解决了吗？

**Comment by lynlynnlynnn** [comment]
同问，请问解决了吗？

**Comment by TENGSP** [comment]
> 在运行到crf模型时出现上述错误，查了很久，试了各种方法也没有解决，请问有没有人知道该如何解决呢？
> 环境：win10 python3.8
> 编码方式查过了是utf-8没错，但一直出现这个错误。求大神支招！

求解决方法

**Comment by lln1997** [comment]
只能用linux运行

**Comment by BlackSpritee** [comment]
找到报错的地方，变量名加str()转换一下，

**Comment by hujunyi96** [comment]
在字符串前加小写r

**Comment by 1yangjianfei** [comment]
同问，请问解决了吗

**Comment by Hai-Chao-ren** [comment]
同问，在linux上运行crf时出现了这个问题

**Comment by jiayuanyuan67777** [comment]
我也遇到这个问题，求问怎么解决

**Comment by EstrellaXiao** [comment]
> 找到报错的地方，变量名加str()转换一下，

您好，请问是要加在哪里呢？

正在训练评估CRF模型...
Traceback (most recent call last):
  File "D:\named_entity_recognition-master\named_entity_recognition-master\main.py", line 73, in <module>
    main()
  File "D:\named_entity_recognition-master\named_entity_recognition-master\main.py", line 29, in main
    crf_pred = crf_train_eval(
  File "D:\named_entity_recognition-master\named_entity_recognition-master\evaluate.py", line 43, in crf_train_eval
    crf_model.train(str(train_word_lists), str(train_tag_lists))
  File "D:\named_entity_recognition-master\named_entity_recognition-master\models\crf.py", line 23, in train
    self.model.fit(str(features), str(tag_lists))
  File "D:\anaconda\lib\site-packages\sklearn_crfsuite\estimator.py", line 331, in fit
    trainer.train(self.modelfile.name, holdout=-1 if X_dev is None else 1)
  File "pycrfsuite/_pycrfsuite.pyx", line 359, in pycrfsuite._pycrfsuite.BaseTrainer.train
  File "<stringsource>", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)
